### ISSUE TITLE
Implementing generic paint and readout for mesh-TF implementation

### ISSUE THREAD

**Issue by modichirag** [modichirag/flowpm#53]
As far as I can see, I don't think the current implementation trivially accommodates a generic catalog of positions, randomly shuffled, for painting and readout.
Currently mesh_utils.cic_paint takes in the tensor 'part' which is particle positions of the shape [batch, nx, ny, nz, 3]
A generic paint or readout function needs [batch, npart, 3], along with associated functions to determine which rank the particle belongs to. 
This needs to be implemented.

**Comment by modichirag** [comment]
Some thoughts - 
say we have a Nx3 tensor of positions that we want to paint (ignore batch for now) 

- the simplest way might be to replicate the tensor on every rank, see if the particular row falls into the grid position on that rank and paint it. Ignore others. Highly memory inefficient. 
- the idea way will be to split the particles and send the particles to the ranks that their position corresponds to. Immediate problem with this is variable length of tensor in different rank. Does TF and MTF support that?

This is where it gets controversial -- do we even need this?

I am thinking of 2 different types of species

1. _dynamic_ : whose position evolves with time, or as a part of the computation. We need a paint and readout function for these. We have it for dark matter particles right now. It is a specialized function since it assumes that we have N^3 particles where N is also the grid size and paint and readout operations, as far as I can see, are built upon that.
Question - is this enough? Do we think of any other dynamic species, esp that will not follow this N^3 assumption. If so, we might need a generic paint and readout, if not then maybe what we have is sufficient? 
2. _static_ species : these are those for which the position will not change over the computation. If so, maybe we can just give up on the concept of position here, use nbodykit or single process flowpm paint option to paint these positions on the grid ahead of the MTF computation and simply use that grid. 

So, do we need to spend energy on this issue or should we drop it for now and come back to it later if we need it.

**Comment by EiffL** [comment]
Yes, so to your first point, we don't want send particles around, because it will quickly become a nightmare of automatic differentiation. 

to your second point...... our current approach is that particles are co-located from the start with the portion of the mesh they should be painted on. And at no point do we try to redistribute them during computation. To avoid border effects, we have these extra padding regions, but if a particle moves beyond the padding, then we are in trouble.

So the question is just, do you have a use case where particles can stream very far away from their initial positions? So much so we would need to redistribute them at some point in the computation?

**Comment by modichirag** [comment]
Depending on how this goes, maybe we should rename the paint and readout operations in current mtfp functions to differentiate from the actual cic_paint and readout in traditional sense.

**Comment by EiffL** [comment]
but why? they are exaclty the traditional cic paint and readout. They are just very specialized to a given way to distribute the particles.
